homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

  allowlist_external_dirs:
    - "/tmp/"

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        # Home VLANs
        - 192.168.0.0/24
        - 192.168.10.0/24
        - 192.168.20.0/24
        # Wireguard
        - 172.17.0.1
      allow_bypass_login: true
      trusted_users:
        # Josh
        # - JOSH-PC
        192.168.10.10: e4d41cea96f74502b7862efedc2537e0
        # - Galaxy S20
        192.168.10.20: e4d41cea96f74502b7862efedc2537e0
        # - Surface Laptop
        192.168.10.30: e4d41cea96f74502b7862efedc2537e0
        # Wireguard clients
        192.168.2.2: e4d41cea96f74502b7862efedc2537e0
        192.168.2.3: e4d41cea96f74502b7862efedc2537e0
    - type: homeassistant

http:
  ip_ban_enabled: true
  login_attempts_threshold: 50
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.10.102

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

default_config:
lovelace:
config:
hassio:
system_health:
history:
logbook:
mobile_app:
input_boolean:
input_number:
recorder:
sun:

tts:
  - platform: google_translate
    service_name: google_say

logger:
  default: warning

plant:
  money_tree:
    sensors:
      moisture: sensor.money_tree_moisture
      battery: sensor.money_tree_battery
      temperature: sensor.money_tree_temperature
      conductivity: sensor.money_tree_conductivity
      brightness: sensor.money_tree_illuminance
    min_moisture: 15

media_player:
  - platform: universal
    name: Currently Playing
    children:
      - media_player.dining_room
      - media_player.living_room
      - media_player.living_room_shield
      - media_player.kitchen_display
      - media_player.office_speaker
      - media_player.master_bedroom_tv
      - media_player.master_bedroom
      - media_player.master_bathroom

google_assistant:
  project_id: divine-axis-138402
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - alarm_control_panel
    #- camera
    - fan
    - switch
    - light
    - lock
    - media_player
    - vacuum
    - cover

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: CA

notify:
  - platform: group
    name: all_phones
    services:
      - service: mobile_app_josh_phone
        data:
          data:
            ttl: 0
            priority: high
      - service: mobile_app_ayda_phone
        data:
          data:
            push:
              interruption-level: time-sensitive
# camera:
#   - platform: proxy
#     entity_id: camera.garage_camera_high_resolution_channel
#     mode: crop
#     # max_image_width: 480
#     # max_image_height: 320
#     # max_stream_width: 480
#     # max_stream_height: 320
#     image_left: 300
#     max_image_width: 200
#     max_image_height: 200
#     max_stream_height: 200
#     max_stream_width: 200
